name: topas docker deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  docker-topas:
    name: alma9 geant4.1.3 TOPAS docker
    runs-on: ubuntu-latest

    steps:
      - name: Dump job context
        env:
        JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }} 

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-g4.11.1-topas

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.github/docker/alma9-g4.11.1-topas
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#  apptainer-topas:
#    - name: alma9 geant4.1.3 TOPAS apptainer
#    - runs-on: ubuntu-latest